version: "3"

services:
  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - POSTMARK_TOKEN=${POSTMARK_TOKEN}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - ENV=production
    volumes:
      - ./backend:/app/backend
      - ./certs:/app/certs
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hpg
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 