"""Add autoincrement to user_history id

Revision ID: 7f9e3ac05b72
Revises: cee0a238c0d6
Create Date: 2025-04-09 17:09:03.494168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9e3ac05b72'
down_revision: Union[str, None] = 'cee0a238c0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_history_id', table_name='user_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_history_id', 'user_history', ['id'], unique=False)
    # ### end Alembic commands ###
