name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        # Store the PEM key with proper formatting
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem
        # Disable strict host key checking for deployment
        echo "Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null" > ~/.ssh/config
          
    - name: Get remote home directory
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      id: get_home
      run: |
        REMOTE_HOME=$(ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST 'echo $HOME')
        echo "REMOTE_HOME=$REMOTE_HOME" >> $GITHUB_ENV
        echo "Remote home directory: $REMOTE_HOME"

    - name: Debug SSH connection
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "Testing connection to $EC2_HOST as user $EC2_USERNAME..."
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST 'echo SSH connection successful; echo User home: $HOME; ls -la $HOME'

    - name: Install rsync on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "Installing rsync on EC2 instance..."
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "sudo apt-get update && sudo apt-get install -y rsync"

    - name: Create docker-compose.yml
      run: |
        echo 'version: "3"' > docker-compose.yml
        echo '' >> docker-compose.yml
        echo 'services:' >> docker-compose.yml
        echo '  backend:' >> docker-compose.yml
        echo '    build: .' >> docker-compose.yml
        echo '    restart: always' >> docker-compose.yml
        echo '    ports:' >> docker-compose.yml
        echo '      - "8000:8000"' >> docker-compose.yml
        echo '      - "443:443"' >> docker-compose.yml
        echo '    env_file:' >> docker-compose.yml
        echo '      - .env' >> docker-compose.yml
        echo '    volumes:' >> docker-compose.yml
        echo '      - ./backend:/app/backend' >> docker-compose.yml
        echo '      - ./certs:/app/certs' >> docker-compose.yml
        echo '    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile", "/app/certs/key.pem", "--ssl-certfile", "/app/certs/cert.pem"]' >> docker-compose.yml

    - name: Create Dockerfile
      run: |
        echo 'FROM python:3.13-slim' > Dockerfile
        echo '' >> Dockerfile
        echo 'WORKDIR /app' >> Dockerfile
        echo '' >> Dockerfile
        echo '# Install build tools and Cairo dev libraries needed for PyCairo' >> Dockerfile
        echo 'RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc libcairo2-dev pkg-config && rm -rf /var/lib/apt/lists/*' >> Dockerfile
        echo '' >> Dockerfile
        echo 'COPY backend/requirements.txt .' >> Dockerfile
        echo '# Debug: List files and show requirements.txt content' >> Dockerfile
        echo 'RUN ls -la /app' >> Dockerfile
        echo 'RUN cat /app/requirements.txt' >> Dockerfile
        echo '# Update pip before installing requirements' >> Dockerfile
        echo 'RUN python -m pip install --upgrade pip' >> Dockerfile
        echo 'RUN pip install --no-cache-dir -r requirements.txt' >> Dockerfile
        echo '' >> Dockerfile
        echo 'COPY backend /app/backend' >> Dockerfile
        echo '' >> Dockerfile
        echo 'WORKDIR /app/backend' >> Dockerfile
        echo '' >> Dockerfile
        echo 'CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]' >> Dockerfile

    - name: Copy files to EC2 using rsync
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # Create the main app directory
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "mkdir -p $REMOTE_HOME/app"
        
        # Sync backend directory, excluding __pycache__
        echo "Syncing backend directory..."
        rsync -avz --delete --exclude='__pycache__' -e "ssh -i ~/.ssh/ec2-key.pem" ./backend/ $EC2_USERNAME@$EC2_HOST:$REMOTE_HOME/app/backend/
        
        # Sync docker-compose.yml
        echo "Syncing docker-compose.yml..."
        rsync -avz -e "ssh -i ~/.ssh/ec2-key.pem" ./docker-compose.yml $EC2_USERNAME@$EC2_HOST:$REMOTE_HOME/app/
        
        # Sync Dockerfile
        echo "Syncing Dockerfile..."
        rsync -avz -e "ssh -i ~/.ssh/ec2-key.pem" ./Dockerfile $EC2_USERNAME@$EC2_HOST:$REMOTE_HOME/app/

    - name: Install Docker and Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "
          set -e # Exit immediately if a command exits with a non-zero status.
          # Check if jq is installed, install if not
          if ! command -v jq &> /dev/null; then
            echo 'jq not found, installing...'
            sudo apt-get update && sudo apt-get install -y jq
          fi
          
          # Install Docker if not already installed
          if ! command -v docker &> /dev/null; then
            echo 'Installing Docker...'
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository -y 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' # Assuming Debian Buster, adjust if needed
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker \$USER # Correctly escape $USER for remote execution
            echo 'Docker installation completed. You might need to re-login for group changes to apply.'
          else
            echo 'Docker is already installed'
          fi
          
          # Install Docker Compose v2
          if ! docker compose version &> /dev/null; then # Check using 'docker compose' command
            echo 'Installing Docker Compose v2 (as plugin)...'
            # Use jq to safely get the latest version tag
            LATEST_COMPOSE_VERSION=\$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
            echo "Latest Docker Compose version: \$LATEST_COMPOSE_VERSION"
            DOCKER_CONFIG=${DOCKER_CONFIG:-\$HOME/.docker}
            sudo mkdir -p \$DOCKER_CONFIG/cli-plugins
            sudo curl -SL "https://github.com/docker/compose/releases/download/\$LATEST_COMPOSE_VERSION/docker-compose-linux-x86_64" -o \$DOCKER_CONFIG/cli-plugins/docker-compose
            sudo chmod +x \$DOCKER_CONFIG/cli-plugins/docker-compose
            # Verify installation
            docker compose version
            echo 'Docker Compose installation completed'
          else
            echo 'Docker Compose v2 plugin is already installed'
          fi
        "

    - name: Generate SSL certificates
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "
          cd $REMOTE_HOME/app &&
          mkdir -p certs &&
          cd certs &&
          openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365 -subj '/CN=localhost'
        "

    - name: Deploy with Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        POSTMARK_TOKEN: ${{ secrets.POSTMARK_TOKEN }}
        FRONTEND_BASE_URL: ${{ secrets.FRONTEND_BASE_URL }}
        ENVIRONMENT: "production"
      run: |
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "
          cd $REMOTE_HOME/app && 
          echo "DB_URL=$DB_URL" > .env &&
          echo "SECRET_KEY=$SECRET_KEY" >> .env &&
          echo "POSTMARK_TOKEN=$POSTMARK_TOKEN" >> .env &&
          echo "FRONTEND_BASE_URL=$FRONTEND_BASE_URL" >> .env &&
          echo "ENV=$ENVIRONMENT" >> .env &&
          echo "CORS_ORIGINS=https://www.hpggrind.se" >> .env &&
          
          # Use Docker Compose v2 command
          docker compose down || echo 'No existing containers to stop'
          docker compose up -d --build
        "
