name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        # Store the PEM key with proper formatting
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem
        # Disable strict host key checking for deployment
        echo "Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null" > ~/.ssh/config
          
    - name: Get remote home directory
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      id: get_home
      run: |
        REMOTE_HOME=$(ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST 'echo $HOME')
        echo "REMOTE_HOME=$REMOTE_HOME" >> $GITHUB_ENV
        echo "Remote home directory: $REMOTE_HOME"

    - name: Debug SSH connection
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "Testing connection to $EC2_HOST as user $EC2_USERNAME..."
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST 'echo SSH connection successful; echo User home: $HOME; ls -la $HOME'

    - name: Create docker-compose.yml
      run: |
        echo 'version: "3"' > docker-compose.yml
        echo '' >> docker-compose.yml
        echo 'services:' >> docker-compose.yml
        echo '  backend:' >> docker-compose.yml
        echo '    build: .' >> docker-compose.yml
        echo '    restart: always' >> docker-compose.yml
        echo '    ports:' >> docker-compose.yml
        echo '      - "8000:8000"' >> docker-compose.yml
        echo '    env_file:' >> docker-compose.yml
        echo '      - .env' >> docker-compose.yml
        echo '    volumes:' >> docker-compose.yml
        echo '      - ./backend:/app/backend' >> docker-compose.yml

    - name: Create Dockerfile
      run: |
        echo 'FROM python:3.9-slim' > Dockerfile
        echo '' >> Dockerfile
        echo 'WORKDIR /app' >> Dockerfile
        echo '' >> Dockerfile
        echo 'COPY backend/requirements.txt .' >> Dockerfile
        echo 'RUN pip install --no-cache-dir -r requirements.txt' >> Dockerfile
        echo '' >> Dockerfile
        echo 'COPY backend /app/backend' >> Dockerfile
        echo '' >> Dockerfile
        echo 'WORKDIR /app/backend' >> Dockerfile
        echo '' >> Dockerfile
        echo 'CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]' >> Dockerfile

    - name: Copy files to EC2 using SCP
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # First create the app directory structure with explicit path
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "mkdir -p $REMOTE_HOME/app/backend"
        
        # Use scp with explicit remote path
        echo "Copying backend directory..."
        scp -i ~/.ssh/ec2-key.pem -r ./backend/* $EC2_USERNAME@$EC2_HOST:$REMOTE_HOME/app/backend/
        
        echo "Copying docker-compose.yml..."
        scp -i ~/.ssh/ec2-key.pem ./docker-compose.yml $EC2_USERNAME@$EC2_HOST:$REMOTE_HOME/app/
        
        echo "Copying Dockerfile..."
        scp -i ~/.ssh/ec2-key.pem ./Dockerfile $EC2_USERNAME@$EC2_HOST:$REMOTE_HOME/app/

    - name: Install Docker and Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "
          # Install Docker if not already installed
          if ! command -v docker &> /dev/null; then
            echo 'Installing Docker...'
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker \$USER
            echo 'Docker installation completed'
          else
            echo 'Docker is already installed'
          fi
          
          # Install Docker Compose v2
          if ! command -v docker-compose &> /dev/null; then
            echo 'Installing Docker Compose...'
            DOCKER_COMPOSE_VERSION=\$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo curl -SL https://github.com/docker/compose/releases/download/\${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            sudo ln -sf /usr/local/lib/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
            echo 'Docker Compose installation completed'
          else
            echo 'Docker Compose is already installed'
          fi
        "

    - name: Create requirements.txt on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "
          if [ ! -f $REMOTE_HOME/app/backend/requirements.txt ]; then
            echo 'Creating requirements.txt'
            echo 'fastapi>=0.68.0' > $REMOTE_HOME/app/backend/requirements.txt
            echo 'uvicorn>=0.15.0' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'sqlalchemy>=1.4.23' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'psycopg2-binary>=2.9.1' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'python-jose>=3.3.0' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'passlib>=1.7.4' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'python-multipart>=0.0.5' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'pydantic>=1.8.2' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'bcrypt>=3.2.0' >> $REMOTE_HOME/app/backend/requirements.txt
            echo 'python-dotenv>=0.19.0' >> $REMOTE_HOME/app/backend/requirements.txt
          fi
        "

    - name: Deploy with Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        ssh -i ~/.ssh/ec2-key.pem $EC2_USERNAME@$EC2_HOST "
          cd $REMOTE_HOME/app && 
          echo \"DATABASE_URL=$DATABASE_URL\" > .env &&
          echo \"SECRET_KEY=$SECRET_KEY\" >> .env &&
          
          # Run docker-compose
          docker-compose down || echo 'No existing containers to stop'
          docker-compose up -d --build
        "
