name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.EC2_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Debug SSH connection
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "Testing connection to $EC2_HOST..."
        # Verbose ssh attempt with 10 second timeout
        ssh -v -o ConnectTimeout=10 -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST 'echo SSH connection successful'
      continue-on-error: true

    - name: Check EC2 connectivity
      run: |
        echo "Checking if host is reachable..."
        ping -c 4 ${{ secrets.EC2_HOST }}
      continue-on-error: true

    - name: Copy files to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # Create remote directory if it doesn't exist
        ssh -i ~/.ssh/id_rsa -o ConnectTimeout=10 $EC2_USERNAME@$EC2_HOST 'mkdir -p /home/$EC2_USERNAME/app/backend/' || echo "Could not create directory, continuing..."
        
        # Try with higher timeout values and less verbosity for actual file transfer
        rsync -az --timeout=60 --delete \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=30" \
          ./backend/ \
          $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/app/backend/
        
        rsync -az --timeout=60 \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=30" \
          ./docker-compose.yml \
          $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/app/
        
        rsync -az --timeout=60 \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=30" \
          ./Dockerfile \
          $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/app/

    - name: Deploy with Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        ssh -i ~/.ssh/id_rsa -o ConnectTimeout=30 $EC2_USERNAME@$EC2_HOST '
          cd /home/$EC2_USERNAME/app && 
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env &&
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env &&
          docker-compose down &&
          docker-compose up -d --build
        '
