name: Manual Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'settings.py'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          
        
  